name: ci

on:
  push:
    branches: [ main ]   # runs automatically on push to main
  workflow_dispatch: {}   # allows manual trigger from the Actions tab

permissions:
  id-token: write         # needed for OIDC federation with AWS
  contents: read          # allows checkout of repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-session-name: gha-condor-build

      - name: Verify AWS caller
        run: aws sts get-caller-identity

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          make build-push ACCOUNT_ID=$ACCOUNT_ID AWS_REGION=us-west-2