name: ci

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show GitHub context (repo/branch)
        run: |
          echo "repo=${{ github.repository }}"
          echo "ref=${{ github.ref }}"
          echo "role=${{ vars.AWS_ROLE_TO_ASSUME }}"

      - name: Ensure role ARN is set
        run: |
          if [ -z "${{ vars.AWS_ROLE_TO_ASSUME }}" ]; then
            echo "ERROR: repo Actions Variable AWS_ROLE_TO_ASSUME is empty or missing."
            echo "Add it in Settings → Actions → Variables, or let Terraform create it."
            exit 1
          fi

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-session-name: gha-condor-build

      - name: Verify AWS caller
        run: aws sts get-caller-identity

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          make build-push ACCOUNT_ID=$ACCOUNT_ID AWS_REGION=us-west-2