name: ci
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          export ACCOUNT_ID
          make build-push ACCOUNT_ID=$ACCOUNT_ID AWS_REGION=us-west-2
